services:
  tp-bioinfo:
    build: .
    image: tp-bioinfo:latest
    container_name: bioinf_tp_app
    # Los JSON generados en /app/output quedan disponibles en ./output del host.
    volumes:
      - ./output:/app/output
